version: '3'
services:
  model_db:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
    command: uvicorn src.api.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
